language: php

dist: bionic

php:
  - '7.3'
  - '7.4'
  - '8.0'
  - '8.1.0'

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit
